### ISSUE TITLE
如何使用ziya-coding微调专有API

### ISSUE THREAD

**Issue by liudonglei** [IDEA-CCNL/Ziya-Coding#2]
https://zhuanlan.zhihu.com/p/644509601
这个报告里讲的【2 使用ziya-coding微调】里的量化策略这个例子，有没有没有相关的代码？

**Comment by pskun** [comment]
> https://zhuanlan.zhihu.com/p/644509601 这个报告里讲的【2 使用ziya-coding微调】里的量化策略这个例子，有没有没有相关的代码？

你可以使用fastchat等开源框架进行微调。
